B4J=true
Group=Handlers
ModulesStructureVersion=1
Type=Class
Version=10.2
@EndOfDesignText@
'Handler class
Sub Class_Globals
	Private Response As ServletResponse
	Private Method As String
End Sub

Public Sub Initialize

End Sub

Sub Handle (req As ServletRequest, resp As ServletResponse)
	Response = resp
	Method = req.Method.ToUpperCase
	Dim path As String = req.RequestURI
	If path = "/" Then
		If Method = "GET" Then
			ShowIndexPage
			Return
		End If
	Else If path = "/modal" Then
		If Method = "POST" Then
			Response.Write(GenerateModal)
			Return
		End If
		Response.SendError(405, "<h1>405 Method Not Allowed</h1>")
		Return
	End If
	Response.SendError(404, "<h1>404 Page Not Found</h1>")
End Sub

Private Sub ShowIndexPage
	Dim doc As Document
	doc.Initialize
	doc.AppendDocType
	doc.Append(GenerateIndex)
	Response.Write(doc.ToString)
End Sub

Sub GenerateIndex As String
	Dim html1 As Tag = Html.lang("en")
	html1.comment(" generated by MiniHTML ")
	Head.up(html1).responsive.title("HTMX Demo") _
	.cdnStyle("https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css", "sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC") _
	.cdnScript("https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js", "sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM") _
	.cdnScript("https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js", "sha384-/TgkGk7p307TH7EXJDuUlgG3Ce1UVolAOFopFekQkkXihi5u/6OCvVKyz1W+idaz")

	Dim body1 As Tag = Body.up(html1)
	Dim div1 As Tag = Div.cls("d-flex align-items-center").sty("height: 100vh").up(body1)
	Dim div2 As Tag = Div.sty("margin: auto").up(div1)

	Dim div3 As Tag = Div.id("modals-here").cls("modal modal-blur fade").sty("display: none") _
	.aria("hidden", "false").attr("tabindex", "-1").up(div2)
	Dim div4 As Tag = Div.cls("modal-dialog modal-lg modal-dialog-centered").attr("role", "document").up(div3)
	Div.cls("modal-content").up(div4)

	Button.up(div2).hxPost("/modal") _
	.hxTarget("#modals-here") _
	.hxTrigger("click") _
	.data("bs-toggle", "modal") _
	.data("bs-target", "#modals-here") _
	.cls("btn btn-primary text-uppercase") _
	.Text("Open Modal").uniline

	Return html1.Build
End Sub

Sub GenerateModal As String
	Dim div4 As Tag = Div.cls("modal-dialog modal-lg modal-dialog-centered")
	Dim div5 As Tag = Div.cls("modal-content").up(div4)
	Dim div6 As Tag = Div.cls("modal-header").up(div5)
	H5.cls("modal-title").Text("Modal title").up(div6)
	Dim div6 As Tag = Div.cls("modal-body").up(div5)
	Paragraph.Text("Modal body text goes here.").uniline.up(div6)
	Dim div6 As Tag = Div.cls("modal-footer").up(div5)
	Button.typeOf("button") _
	.cls("btn btn-secondary text-uppercase") _
	.data("bs-dismiss", "modal") _
	.Text("Close").up(div6).uniline
	Return div4.Build
End Sub